baseURL = "/"
languageCode = "en-us"
title = "Hugo Starter"
markup.highlight.noClasses = false
summaryLength = 30
disableKinds = ["taxonomyTerm"]

[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'
